# This workflow will do a clean install of node dependencies, build the source code and push the binaries to the deployment repository.
name: Build & Deploy master

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.13.1]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: corepack enable
            - run: yarn install --network-concurrency 1 --frozen-lockfile
            - run: yarn run build-hash
            - name: Create CNAME file
              uses: finnp/create-file-action@master
              env:
                  FILE_NAME: build/hash-history/CNAME
                  FILE_DATA: wallet.bitshares.org
            - name: Deploy
              uses: s0/git-publish-subdir-action@master
              env:
                  REPO: git@github.com:bitshares/wallet.bitshares.org.git
                  BRANCH: master
                  FOLDER: build/hash-history
                  SSH_PRIVATE_KEY: ${{ secrets.AUTOMATION_MASTER_DEPLOYMENT_KEY }}
